### PR TITLE
Fix re-auth during serivce refresh. Fixes #394

### LINKED ISSUE #394: SDK does not recover from API session expiration (during app/computer suspend)
```
ERRO[4080] failed to load service updates [GET /services][401] listServicesUnauthorized  &{Error:0xc0009abec0 Meta:0xc00084ee80} 
ERRO[4110] failed to load service updates [GET /services][401] listServicesUnauthorized  &{Error:0xc000958060 Meta:0xc0006107c0} 
```

### PR DESCRIPTION
**Pull request by plorenz**

### CODE REVIEW

File: ziti/client.go [hunk 1]
```diff
@@ -63,18 +62,14 @@ func (self *CtrlClient) Refresh() (*time.Time, error) {
 // IsServiceListUpdateAvailable will contact the controller to determine if a new set of services are available. Service
 // updates could entail gaining/losing services access via policy or runtime authorization revocation due to posture
 // checks.
-func (self *CtrlClient) IsServiceListUpdateAvailable() (bool, error) {
```
Comment (plorenz) [inline ziti/client.go:66]: lastServiceUpdate was never getting set, so this always returned nil

**Review by andrewpmartinez — APPROVED** [review]
